### ISSUE TITLE
Grading Overview

### ISSUE THREAD

**Issue by lucav17** [Lauturala/prj-rev-bwfs-dasmoto#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4
* _Comment(s):_ Well done including your CSS file in your HTML!
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_  4
* _Comment(s):_  Great job replicating the spec! The overall site looks well put together!
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4
* _Comment(s):_  Overall I think you had great structure in your HTML! I enjoyed how you wrapped the sections in divs.
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4
* _Comment(s):_ Great job optimizing your CSS to create non repetitive CSS structures. this is good for page loading.
 
### Overall Score: 16/16
Well done!

**Comment by Lauturala** [comment]
Thanks a lot!
